server:
  port: 8089

logging:
  level:
    com:
      mdomonkos:
        crypto: DEBUG
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rate-limiter:
  enabled: false
  max: 1
  window: 10