apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: recommendation-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_HOST
              value: postgres
#            - name: SPRING_PROFILES_ACTIVE
#              value: dev
          imagePullPolicy: Never # local image
#          imagePullPolicy: Always # remote image
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer